name = "telegram-wildcard-bot"

account_id = "<your-account-id>"  # Ganti dengan ID akun Cloudflare kamu
workers_dev = true

compatibility_date = "2025-06-02"
main = "worker.js"  # Sesuaikan dengan nama file Worker utama kamu, misal worker.js

[vars]
ROOT_DOMAIN = "joss.checker-ip.xyz"
