name = "telegram-wildcard-bot"

account_id = "e9930d5ca683b0461f73477050fee0c7"  # Ganti dengan ID akun Cloudflare kamu
workers_dev = true

compatibility_date = "2025-06-02"
main = "worker.js"  # Sesuaikan dengan nama file Worker utama kamu, misal worker.js

[vars]
ROOT_DOMAIN = "joss.checker-ip.xyz"
