name = "telegram-wildcard-bot"
type = "javascript"

account_id = "<your-account-id>"
workers_dev = true
route = ""
zone_id = ""

[vars]
ROOT_DOMAIN = "joss.checker-ip.xyz"

[secrets]
TELEGRAM_TOKEN = "your-telegram-bot-token"
OWNER_ID = "123456789"
ACCOUNT_ID = "e9930d5ca683b0461f73477050fee0c7"
ZONE_ID = "80423e7547d2fa85e13796a1f41deced"
API_KEY = "5fae9fcb9c193ce65de4b57689a94938b708e"
API_EMAIL = "ambebalong@gmail.com"
SERVICE_NAME = "siren"
