name: Deploy Wildcard Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare Worker
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler deploy
