name: Deploy Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler latest globally
        run: npm install -g wrangler@latest

      - name: Deploy Worker with Wrangler
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: wrangler deploy
